### ISSUE TITLE
Stack trace in console 

### ISSUE THREAD

**Issue by akondasif** [mgubaidullin/karamel#3]
Greetings,

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of improper exception handling.

According to CWE, stack traces due to exception handling should not be printed. See https://cwe.mitre.org/

Source: https://github.com/mgubaidullin/karamel/blob/master/.mvn/wrapper/MavenWrapperDownloader.java

Fix: https://github.com/mgubaidullin/karamel/pull/2

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by mgubaidullin** [comment]
This code runs during project build and not a part of produced application

**Comment by mgubaidullin** [comment]
This code runs during project build and not a part of produced application
